// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPHn-ALI50Ai3TveN2SeEEtWAm918SPkQ',
    appId: '1:106493446273:web:72e3c631c76aa2eaa76580',
    messagingSenderId: '106493446273',
    projectId: 'myproject-a9913',
    authDomain: 'myproject-a9913.firebaseapp.com',
    storageBucket: 'myproject-a9913.appspot.com',
    measurementId: 'G-VNE6SRJ2HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAOeMvZ1iIVKM4e4jTdQUql5VIpR-T_lc',
    appId: '1:106493446273:android:dee2f88661238149a76580',
    messagingSenderId: '106493446273',
    projectId: 'myproject-a9913',
    storageBucket: 'myproject-a9913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6rCly8vqwD8ZTc4a5MTJgxBPD4gW5tVQ',
    appId: '1:106493446273:ios:4ff2b1c70a132059a76580',
    messagingSenderId: '106493446273',
    projectId: 'myproject-a9913',
    storageBucket: 'myproject-a9913.appspot.com',
    iosClientId: '106493446273-m4hq66l5d6ttf97d6lf5jp88j9r2od1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6rCly8vqwD8ZTc4a5MTJgxBPD4gW5tVQ',
    appId: '1:106493446273:ios:777eb46fefc1fb3ea76580',
    messagingSenderId: '106493446273',
    projectId: 'myproject-a9913',
    storageBucket: 'myproject-a9913.appspot.com',
    iosClientId: '106493446273-d56kbhkff2t2vh1gmqarpdr8shfl8afe.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject.RunnerTests',
  );
}
